/* eslint-disable  no-unused-vars, no-undef */
import $ from 'jquery';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import initPlugins from './plugins/init';
import initHeader from './template-parts/header';
import initHero from './template-parts/hero';
import initTwoThumbs from './modules/two-thumbs';
import initSlider from './modules/slider';
import initImageVideoText from './modules/image-video-text';
import initCtaContact from './modules/cta-contact';
import initBigSmallThumbs from './modules/big-small-thumbs';
import initText from './modules/text';
import initDoubleVideoImage from './modules/double-video-image';
import initFullViewportImage from './modules/full-viewport-image';
import initThreeThumbs from './modules/three-thumbs';
import initFourThumbs from './modules/four-thumbs';
import initContactTeaser from './modules/contact-teaser';
import initThumb8Col from './modules/thumb-8col';
import initCta from './modules/cta';
import initEmployeesOfficesFinder from './modules/employees-offices-finder';
import initSectorsGrid from './modules/sectors-grid';
import initServicesGrid from './modules/services-grid';
import initOfficeEmployees from './modules/office-employees';
import initHeroEmployee from './modules/hero-employee';

$(function () {
	initPlugins();
	initHeader();
	initHero();
	initTwoThumbs();
	initSlider();
	initImageVideoText();
	initCtaContact();
	initBigSmallThumbs();
	initText();
	initDoubleVideoImage();
	initFullViewportImage();
	initThreeThumbs();
	initFourThumbs();
	initContactTeaser();
	initThumb8Col();
	initCta();
	initEmployeesOfficesFinder();
	initSectorsGrid();
	initServicesGrid();
	initOfficeEmployees();
	initHeroEmployee();
});
